name: Docker Build Deploy
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2


      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Login to Github Package
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build images and push to Docker Hub and Github container Registry
        uses: docker/build-push-action@v4
        id: build-and-push
        with:
          context: ./
          push: true
          tags: |
            liquid07/k8s-ha:${{ github.sha }}
#          ghcr.io/liquid07/k8s-ha:${{ github.sha }}
            
          
      - name: Image digest
        run: |
          echo liquid07/k8s-ha:${{ github.sha }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.actor }}/k8s-ha
          ref: 'main'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: set git config
        run: |
          git config --global user.email "patiwat.srisutham@gmail.com"
          git config --global user.name "patiwat13"
          echo ${{ github.sha }}
          sed -e "s#liquid07.*#liquid07/k8s-ha:${{ github.sha }}#g" k8s-nginx-deployment.yaml
          git add k8s-nginx-deployment.yaml
          git commit --amend -m "Update Images"
      - run: echo ${{ github }}
      - run: git push origin main
