name: Docker Build Deploy

on:
  push:
    branches: ['main']

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2


      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build images and push to Docker Hub
        uses: docker/build-push-action@v4
        id: build-and-push
        with:
          context: ./
          push: true
          tags: |
            liquid07/k8s-ha:${{ github.sha }}

  Update-Manifest-Stage:
    runs-on: ubuntu-latest
    needs: ['build-and-push-docker-image']

    steps:
      - uses: actions/checkout@v3
        with:
         repository: ${{ github.actor }}/k8s-ha
         token: ${{ secrets.G_TOKEN }}

      - name: Edit Files
        run: sed -i "s#liquid07.*#liquid07/k8s-ha:${{ github.sha }}#g" k8s-nginx-deployment.yaml k8s-nginx-deployment.yaml

      - name: Display Deploy
        run: cat k8s-nginx-deployment.yaml
  

      - name: Push Change
        run: |
          git config user.email "patiwat.srisutham@gmail.com"
          git config user.name "patiwat13"
          git add -A
          git commit -am "Update Images - ${{ github.sha }}"
          git push
        